import React from 'react'
import { Heading, Headingone } from '../components/Headings';
import TableComponent from '../components/TableComponent';
import { Table, TableBody, TableCell, TableContainer, TableHead, TableRow, Paper, Stack, } from '@mui/material';

const AccountDetailsConfig = {
  registrations: [
  ],
  columns: [
    { field: 'text', headerName: '' },
    { field: 'details', headerName: '' },
  ],
  data: [
    { text: 'Account Name', details: 'IEEE INDIA COUNCIL' },
    { text: 'Account Number', details: '50100016415405' },
    { text: 'RTGS/NEFT Code', details: 'HDFC0000674' },
    { text: 'SWIFT Code', details: 'HDFCINBB' },
    { text: 'Bank Name', details: 'HDFC Bank Ltd' },
    { text: 'Bank Address', details: 'PLOT # 46, DOOR # 23, 1st MAIN ROAD, NANGANALLUR CHENNAI 600061 TAMILNADU (INDIA)' },
  ],
};

const AuthorsGuide = [
  "At least one of the authors of every accepted paper must register for the conference as author and present the paper in order for it to be included in the conference proceedings of INDISCON 2024, and subsequent submission to IEEE Xplore digital library.",
  "If more than one author of an accepted paper wishes to attend the conference, all such authors need to be registered separately by paying applicable registration fee.",
  "Additional authors (other than those who are included in the manuscript submitted for review) cannot be added to the camera-ready paper.",
  "Non-refundable registration fee must be paid prior to uploading the final IEEE formatted, Camera-ready version of the paper and e-copyright form.",
];

const AttendeesGuide = [
  "All participants need to be registered to attend the INDISCON 2024 by paying the requisite registration fee.",
  "The registration fee include the conference kit, access/admission to tutorials & technical sessions, lunch on all conference days, morning and evening refreshments, banquet dinner, access/admission to cultural events as part of the conference.",
  "Please note that the fee shown above are exclusive of all taxes and levies. Any gateway charges along with applicable taxes or levies, if any, will have to be borne by the registrant.",
  "IEEE members are requested to upload IEEE membership details during the online registration process, if registering under IEEE category.",
  "Students are requested to upload valid student ID card (front and back side) during the online registration process, if registering under that student category.",
  "Please keep a copy of the transaction ID, generated by the payment gateway as well as by your bank. You may need these later if you need to track your payment/registration.",
  "All correspondence regarding registration for INDISCON 2024 should contain Paper ID as well as registration confirmation number.",
  "Please note that INDISCON 2024, or the organizing institute, represented by the Organizing Committee as well as the IEEE India Council or IEEE Delhi Section or IEEE Chandigarh Subsection, will not be responsible for any loss, financial or otherwise, caused by improper transactions conducted online. While organizers have taken all reasonable precautions to ensure a safe online transaction, it is the registrant's responsibility, while paying the registration fee, to secure their user IDs, passwords, Paper ID, etc.",
];

const RegistrationConfigs = [
  {
    registrations: [
      { fields: 'first', head: '', span: 1 },
      { fields: 'second', head: 'Early Bird Registration', span: 2 },
      { fields: 'third', head: 'Late Registration', span: 3 },
    ],
    columns: [
      { field: 'category', headerName: 'Category of Authors/Attendees (IEEE Member)' },
      { field: 'IEEEStudent', headerName: 'IEEE Student Members' },
      { field: 'IEEEMem', headerName: 'IEEE Members' },
      { field: 'ieeestudent', headerName: 'IEEE Student Members' },
      { field: 'Ieeemem', headerName: 'IEEE Members' },
    ],
    data: [
      { category: 'Indian Participants', IEEEStudent: "₹5,000", IEEEMem: "₹6,500", Ieeestudent: "₹6,000", Ieeemem: "₹8,000", },
      { category: 'Foreign Participants', IEEEStudent: "$150", IEEEMem: "$250", Ieeestudent: "$250", Ieeemem: "$300", },
      { category: 'Category of Authors/Attendees (Non-IEEE Member)', IEEEStudent: "Non-IEEE Student Members", IEEEMem: "Non-IEEE Members", Ieeestudent: "Non-IEEE Student Members", Ieeemem: "Non-IEEE Members", type: "bold" },
      { category: 'Indian Participants', IEEEStudent: "₹6,000", IEEEMem: "₹8,500", Ieeestudent: "₹7,500", Ieeemem: "₹10,000", },
      { category: 'Foreign Participants', IEEEStudent: "$200", IEEEMem: "$350", Ieeestudent: "$400", Ieeemem: "$450", },
    ],
  },
]



function Registration() {

  return (
    <div style={{ display: 'flex', flexDirection: 'column', justifyContent: "center", alignItems: 'center', gap: "32px", width: '100%', margin: '24px 0px' }}>
      <Headingone text1="Registration" />
      <Stack sx={{ width: '100%' }}>
        {RegistrationConfigs.map((RegistrationConfig, index) => (
          <TableComponent Align="center" tableConfig={RegistrationConfig} />
        ))

        }
      </Stack>
      <Stack sx={{ width: '100%', gap: '20px' }}>
        <Heading size="24px" weight="300" text="For Authors" />
        <Stack sx={{ width: '100%', gap: '20px', paddingLeft: '18px' }}>
          <ol style={{ lineHeight: '25px' }}>
            {AuthorsGuide.map((guide, index) => (
              <li>
                {guide}
              </li>
            ))}
          </ol>
        </Stack>
      </Stack>
      <Stack sx={{ width: '100%', gap: '20px' }}>
        <Heading size="24px" weight="300" text="For Attendees" />
        <Stack sx={{ width: '100%', gap: '20px', paddingLeft: '18px' }}>
          <ol style={{ lineHeight: '25px' }}>
            {AttendeesGuide.map((guide, index) => (
              <li>
                {guide}
              </li>
            ))}
          </ol>
        </Stack>
      </Stack>
      <Stack sx={{ width: '100%', gap: '20px' }}>
        <Heading size="24px" weight="300" text="No Show Policy" />
        <p>
          Any accepted paper included in the final program is expected to have at least one author attend and present the paper at the conference. Non-presented paper will not be submitted to IEEE Xplore digital library as per IEEE no-show policy.
        </p>
      </Stack>
      <Stack sx={{ width: '100%', gap: '20px' }}>
        <Heading size="24px" weight="300" text="Fee Details" />
        <h3 style={{ fontSize: '1.17em' }}>Registration and fee payment for Indian Authors Steps:</h3>
        <p>Click on the following link for paper registeration and fee payment: To be provided soon</p>
        <p style={{ fontWeight: '600' }}>Note: Download the receipt and deposit a copy at conference venue.</p>
        <p>For Foreign Authors only:- Deposit the registration fees through NEFT/RTGS/IMPS/Bank Transfer to the below given bank account and send transaction details to <b style={{ color: '#306fa0', textDecoration: 'underline' }}>ieeeindiscon2024@gmail.com</b>
        </p>
        <TableComponent tableConfig={AccountDetailsConfig} />
      </Stack>
    </div>
  )
}

export default Registration